---
title: "acknowledge"
date: 16/07/2019
documentclass: ctexart
output:
  html_document:
      toc: FALSE
---

	感谢朋克歌手大张伟，是他积极的人生观支撑着我走完这几年的博士之路。
Thanks to the Chinese punk singer Da Zhangwei, his positive outlook on life has supported me in the past few years.

  我头一回看个综艺都会哭
	
	
	大张伟：我的朋友们问我说为什么老在工作，我说音乐对我来说不是工作，那是我一生的使命
	
	我希望我可以早日找到我一生的使命，做科研现在是我的一个可能。
	
	因为大张伟在做音乐的时候，并不是一帆风顺的。在他刚出道的时候，做他想做的音乐并不能养活自己，因此他只能顺应潮流，改变自己的风格。后来在中国做综艺比较火，他也在综艺界找到了位置，小有成就。可喜的是，他也没有放下音乐，相反，综艺的成功，促进他可以在音乐上做到他之前未曾想过的事。在天天向上十周年特辑里，民乐团的大师们改编了大张伟的歌曲，这是大张伟之前从未想到过的事情。 所以说，面对事情并没有向着自己期望的方向发展的时候，不要气馁，也不要拒绝改变，不要拧着，顺应时代的浪潮，同时保持自己的特点，不忘初心，向着太阳走，再不济，总能走到月亮的。
	
	
	
	我仿佛重新回到了我的初二，找到了我奋斗的意义。
	我给自己定下的，为中国获得诺贝尔经济学奖。
	我有些沮丧，我发现我不可能做到，主要有以下几点：
	A1。我数学实力不够，有太多实力强于我的前辈（但是我可以有自己的特色，差异化竞争，科研也是讲究差异化竞争的）做不到就忘了吧
	A2。其实中国之前已经有很多诺贝尔奖了，像文学奖（莫言），医学奖（屠呦呦），物理学奖（李振道，杨振宁），不过确实没有经济学奖。
	
	
	我现在做到的几点：
	B1。通过阅读文献，我发现,我已经进入了计量经济学领域，可我如何在里面找到自己的位置
	B2。通过博士训练，掌握怎么做研究
	
	
	目前就是要通过博士毕业，达到目标B2。
	面对日益困难的竞争，博士很难直接进入高校，拿到位置
	需要有海外的工作经历，时间也是一个很重要的考量。越快越好。想到的解决办法：1。国内博后 2。国外博后
	
	
