---
title: "Work organization and mental health problems in PhD students"
date: "2018/11/21"
---

Research policy observers are increasingly concerned about the potential impact of current academic
working conditions on mental health, particularly in PhD students. The aim of the current study is threefold.
First, we assess the prevalence of mental health problems in a representative sample of PhD students
in Flanders, Belgium (N = 3659). Second, we compare PhD students to three other samples: (1) highly
educatedinthe generalpopulation(N = 769);(2)highly educatedemployees (N = 592); and(3)higher education
students (N = 333). Third, we assess those organizational factors relating to the role of PhD students
that predict mental health status. Results based on 12 mental health symptoms (GHQ-12) showed that
32% of PhD students are at risk of having or developing a common psychiatric disorder, especially depression.
This estimate was significantly higher than those obtained in the comparison groups. Organizational
policies were significantly associated with the prevalence of mental health problems. Especially workfamily
interface, job demands and job control, the supervisor’s leadership style, team decision-making
culture, and perception of a career outside academia are linked to mental health problems.